name: Continuous Dependency Updating

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Install NuGet CLI
      run: |
        dotnet tool install --global nuget.commandline

    - name: Update dependencies
      run: |
        nuget update YourSolution.sln
        dotnet build

    - name: Run tests
      run: |
        dotnet test

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -u
        git commit -m "Update dependencies via CDU" || exit 0
        git push
