name: Continuous Dependency Updating

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Update dependencies
      run: |
        mvn versions:use-latest-versions
        mvn clean install

    - name: Run tests
      run: |
        mvn test

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pom.xml
        git commit -m "Update dependencies via CDU" || exit 0
        git push
