name: Continuous Dependency Updating

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Bundler
      run: |
        gem install bundler

    - name: Update dependencies
      run: |
        bundle update
        bundle install

    - name: Run tests
      run: |
        bundle exec rake test

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Gemfile.lock
        git commit -m "Update dependencies via CDU" || exit 0
        git push
