name: Continuous Dependency Updating

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm ci

    - name: Update dependencies
      run: |
        npm install -g npm-check-updates
        ncu -u
        npm install

    - name: Compile TypeScript
      run: |
        npm install --save-dev typescript
        npx tsc

    - name: Run tests
      run: |
        npm install --save-dev jest ts-jest @types/jest
        npm test

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json package-lock.json
        git commit -m "Update dependencies via CDU" || exit 0
        git push
